// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	UserName string `json:"name"`
	Email    string `json:"email"`
	Phone    int64  `json:"phone"`
	Address  string `json:"address"`
	Gender   int    `json:"gender"`
	Status   string `json:"status"`
	Desc     string `json:"desc"`
	Avatar   string `json:"avatar"`
}

type RegisterRequest struct {
	Info     UserInfo `json:"info"`
	Password string   `json:"password"`
}

type RegisterResponse struct {
	UserId int64 `json:"user_id"`
}

type LoginRequest struct {
	UserName string `json:"user_name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	User_id      int64    `json:"user_id"`
	Info         UserInfo `json:"info"`
	AccessToken  string   `json:"access_token"`
	AccessExpire int64    `json:"access_expire"`
}

type UserInfoRequest struct {
	UserId int64 `json:"user_id"`
}

type UserInfoResponse struct {
	Info UserInfo `json:"info"`
}

type UserUpdateRequest struct {
	UserId int64    `json:"user_id"`
	Info   UserInfo `json:"info"`
}

type UserUpdateResponse struct {
	UserId int64    `json:"user_id"`
	Info   UserInfo `json:"info"`
}
