Name: product.rpc
ListenOn: 127.0.0.1:8080
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
MysqlConf:
  DataSource: root:Cz05180921.@tcp(mysql:3306)/mall?charset=utf8&parseTime=true&loc=Asia%2FShanghai
RedisCache:
  - Host: redis:6379
    Pass:
    Type: node
