Name: productrpc.rpc
ListenOn: 127.0.0.1:8080
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: productrpc.rpc

MysqlDataSource:
  DataSource: root:123456@tcp(mysql:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

RedisCacheConf:
  - Host: redis:6379
    Type: node
