// Code generated by goctl. DO NOT EDIT!
// Source: note.proto

package server

import (
	"context"

	"github.com/lixiandea/go-zero-mall/apps/note/note/internal/logic"
	"github.com/lixiandea/go-zero-mall/apps/note/note/internal/svc"
	"github.com/lixiandea/go-zero-mall/apps/note/note/note"
)

type NoteServer struct {
	svcCtx *svc.ServiceContext
	note.UnimplementedNoteServer
}

func NewNoteServer(svcCtx *svc.ServiceContext) *NoteServer {
	return &NoteServer{
		svcCtx: svcCtx,
	}
}

func (s *NoteServer) GetNote(ctx context.Context, in *note.GetNoteRequest) (*note.GetNoteResponse, error) {
	l := logic.NewGetNoteLogic(ctx, s.svcCtx)
	return l.GetNote(in)
}

func (s *NoteServer) CreateNote(ctx context.Context, in *note.CreateNoteRequest) (*note.CreateNoteResponse, error) {
	l := logic.NewCreateNoteLogic(ctx, s.svcCtx)
	return l.CreateNote(in)
}

func (s *NoteServer) UpdateNote(ctx context.Context, in *note.UpdateNoteRequest) (*note.UpdateNoteResponse, error) {
	l := logic.NewUpdateNoteLogic(ctx, s.svcCtx)
	return l.UpdateNote(in)
}

func (s *NoteServer) DeleteNote(ctx context.Context, in *note.DeleteNoteRequest) (*note.DeleteNoteResponse, error) {
	l := logic.NewDeleteNoteLogic(ctx, s.svcCtx)
	return l.DeleteNote(in)
}
