// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/lixiandea/go-zero-mall/apps/note/noteadmin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/note/GetNote",
				Handler: GetNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/note/DeleteNote",
				Handler: DeleteNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/note/CreateNoteRequest",
				Handler: CreateNoteRequestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/note/UpdateNote",
				Handler: UpdateNoteHandler(serverCtx),
			},
		},
	)
}
