// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/lixiandea/go-zero-mall/apps/note/noteAdmin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/note/getNote",
				Handler: GetNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/note/updateNote",
				Handler: UpdateNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/note/deleteNote",
				Handler: DeleteNoteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/note/addNote",
				Handler: AddNoteHandlersHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
