// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"github.com/lixiandea/go-zero-mall/apps/product/rpc/internal/logic"
	"github.com/lixiandea/go-zero-mall/apps/product/rpc/internal/svc"
	"github.com/lixiandea/go-zero-mall/apps/product/rpc/rpc"
)

type RpcServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedRpcServer
}

func NewRpcServer(svcCtx *svc.ServiceContext) *RpcServer {
	return &RpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RpcServer) Create(ctx context.Context, in *rpc.CreateRequest) (*rpc.CreateResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *RpcServer) Update(ctx context.Context, in *rpc.UpdateRequest) (*rpc.UpdateResponse, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *RpcServer) Remove(ctx context.Context, in *rpc.RemoveRequest) (*rpc.RemoveResponse, error) {
	l := logic.NewRemoveLogic(ctx, s.svcCtx)
	return l.Remove(in)
}

func (s *RpcServer) Detail(ctx context.Context, in *rpc.DetailRequest) (*rpc.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
