// Code generated by goctl. DO NOT EDIT!
// Source: video_rpc.proto

package server

import (
	"context"

	"github.com/lixiandea/go-zero-mall/apps/video/video_rpc/internal/logic"
	"github.com/lixiandea/go-zero-mall/apps/video/video_rpc/internal/svc"
	"github.com/lixiandea/go-zero-mall/apps/video/video_rpc/pb/video_rpc"
)

type VideoRpcServer struct {
	svcCtx *svc.ServiceContext
	video_rpc.UnimplementedVideoRpcServer
}

func NewVideoRpcServer(svcCtx *svc.ServiceContext) *VideoRpcServer {
	return &VideoRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoRpcServer) UpdateVideo(ctx context.Context, in *video_rpc.UpdateVideoRequest) (*video_rpc.UpdateVideoResponse, error) {
	l := logic.NewUpdateVideoLogic(ctx, s.svcCtx)
	return l.UpdateVideo(in)
}

func (s *VideoRpcServer) DeleteVideo(ctx context.Context, in *video_rpc.DeleteVideoRequest) (*video_rpc.DeleteVideoResponse, error) {
	l := logic.NewDeleteVideoLogic(ctx, s.svcCtx)
	return l.DeleteVideo(in)
}

func (s *VideoRpcServer) AddVideo(ctx context.Context, in *video_rpc.AddVideoRequest) (*video_rpc.AddVideoResponse, error) {
	l := logic.NewAddVideoLogic(ctx, s.svcCtx)
	return l.AddVideo(in)
}

func (s *VideoRpcServer) GetVideo(ctx context.Context, in *video_rpc.GetVideoRequest) (*video_rpc.GetVideoResponse, error) {
	l := logic.NewGetVideoLogic(ctx, s.svcCtx)
	return l.GetVideo(in)
}
