// Code generated by goctl. DO NOT EDIT.
package types

type UpdateNoteRequest struct {
	Id      int64  `json:"id"`
	Content string `json:"content"`
}

type UpdateNoteResponse struct {
}

type DeleteNoteRequest struct {
	Id int64 `json:"id"`
}

type DeleteNoteResponse struct {
}

type CreateNoteRequest struct {
	Author  int64  `json:"author"`
	Content string `json:"content"`
}

type CreateNoteResponse struct {
	Id int64 `json:"id"`
}

type GetNoteRequest struct {
	Id int64 `json:"id"`
}

type GetNoteResponse struct {
	Author  int64  `json:"author"`
	Content string `json:"content"`
	Id      int64  `json:"id"`
}
