// Code generated by goctl. DO NOT EDIT.
package types

type UpdateNoteRequest struct {
	Id      int64  `json:"id"`
	Title   string `json:"title"`
	Context string `json:"context"`
	Author  int64  `json:"author"`
}

type UpdateNoteResponse struct {
	Id int64 `json:"id"`
}

type AddNoteRequest struct {
	Title   string `json:"title"`
	Context string `json:"context"`
}

type AddNoteResponse struct {
	Id int64 `json:"id"`
}

type DeleteNoteRequest struct {
	Id int64 `json:"id"`
}

type DeleteNoteResponse struct {
}

type GetNoteRequest struct {
	Id int64 `json:"id"`
}

type GetNoteResponse struct {
	Title   string `json:"title"`
	Context string `json:"context"`
	Author  int64  `json:"author"`
}
